#!/bin/sh

# Mesa3d overwritten files by sunxi-mali
#$ ls -la /usr/lib/libEGL.so*

# Mesa3d files
#lrwxrwxrwx 1 root root  11 Oct  4  2013 /usr/lib/libEGL.so -> libEGL.so.1
#lrwxrwxrwx 1 root root  15 Mar 13 12:39 /usr/lib/libEGL.so.1 -> libEGL.so.1.0.0
#-rwxr-xr-x 1 root root 88K Mar 10 12:23 /usr/lib/libEGL.so.1.0.0

# sunxi-mali files
#lrwxrwxrwx 1 root root  10 Oct  4  2013 /usr/lib/libEGL.so.1.4 -> libMali.so

# Make a backup to restore mesa3d
mv /usr/lib/libEGL.so.1 /usr/lib/libEGL_so_1

# Link to the new file provided by sunxi-mali
ln -s libEGL.so.1.4 /usr/lib/libEGL.so.1
